---
lessonName: Working with REST APIs
lessonId: 19
category: introductory
lessondiagram: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-19/lessondiagram.png
tier: prod

utilities:
- name: linux1
  image: antidotelabs/utility
  sshuser: antidote
  sshpassword: antidotepassword

devices:
- name: vqfx1
  image: antidotelabs/vqfxspeedy:snap1
  sshuser: root
  sshpassword: VR-netlab9
  ports: [8080]
- name: vqfx2
  image: antidotelabs/vqfxspeedy:snap2
  sshuser: root
  sshpassword: VR-netlab9
  ports: [8080]
- name: vqfx3
  image: antidotelabs/vqfxspeedy:snap3
  sshuser: root
  sshpassword: VR-netlab9
  ports: [8080]

connections:
- a: vqfx1
  b: vqfx2
  subnet: 10.12.0.0/24
- a: vqfx2
  b: vqfx3
  subnet: 10.23.0.0/24
- a: vqfx3
  b: vqfx1
  subnet: 10.31.0.0/24
- a: vqfx1
  b: linux1
  subnet: 10.1.0.0/24

stages:
  1:
    id: 1
    description: Your First API Call
    labGuide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-19/stage1/guide.md

  2:
    id: 2
    description: Let's do it with Python!
    labGuide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-19/stage2/guide.md
  # 3:
  #   description: Diving Deep into an API
  #   labguide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-19/stage3/guide.md
