---
lessonName: Docker Containers
lessonID: 31
category: introductory
lessondiagram: https://raw.githubusercontent.com/Sudhishna/antidote/master/lessons/lesson-31/salt.png
tier: local

utilities:
- name: docker1
  image: sudhishna/docker
  sshuser: antidote
  sshpassword: antidotepassword
  ports: [22]

devices:
- name: vqfx1
  image: antidotelabs/vqfxspeedy:snap1
  sshuser: root
  sshpassword: VR-netlab9
  ports: [8080, 830]

connections:
- a: vqfx1
  b: docker1
  subnet: 10.1.0.0/24

stages:
  1:
    description: Docker Images and Containers
    labguide: https://raw.githubusercontent.com/Sudhishna/antidote/master/lessons/lesson-31/stage1/guide.md
