---
lessonName: Network Automation with Salt
lessonId: 30
category: configuration
lessondiagram: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-30/salt.png
tier: prod

utilities:
- name: salt1
  image: antidotelabs/salt
  sshuser: antidote
  sshpassword: antidotepassword
  ports: [22]

devices:
- name: vqfx1
  image: antidotelabs/vqfxspeedy:snap1
  sshuser: root
  sshpassword: VR-netlab9
  ports: [8080, 830]

connections:
- a: vqfx1
  b: salt1
  subnet: 10.1.0.0/24

stages:
  1:
    id: 1
    description: Salt Master and Minion
    labGuide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-30/stage1/guide.md

  2:
    id: 2
    description: Junos Proxy Minions
    labGuide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-30/stage2/guide.md

  3:
    id: 3
    description: Executing Junos commands in Salt
    labGuide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-30/stage3/guide.md
